import { MeetingData } from '../types';

export function generateMarkdownMoM(meeting: MeetingData): string {
  const parts: string[] = [];

  parts.push(`# ${meeting.title}`);
  parts.push(`**Date & Time:** ${meeting.meetingDate} | **Duration:** ${meeting.duration || 'N/A'}`);
  parts.push(`**Meeting Type:** ${meeting.meetingType} | **Detected Language:** ${meeting.languageDetected || 'English'}`);
  parts.push(`**Participants:** ${meeting.participants.join(', ')}`);
  if (meeting.sentiment) {
    parts.push(`**Meeting Tone / Sentiment:** ${meeting.sentiment}`);
  }
  parts.push(`\n---\n`);

  parts.push(`## 📌 Executive Summary`);
  parts.push(meeting.executiveSummary);
  parts.push('');

  if (meeting.decisions && meeting.decisions.length > 0) {
    parts.push(`## 🎯 Key Decisions Made`);
    meeting.decisions.forEach((d, idx) => {
      parts.push(`${idx + 1}. **${d}**`);
    });
    parts.push('');
  }

  if (meeting.actionItems && meeting.actionItems.length > 0) {
    parts.push(`## ✅ Action Items & Owners`);
    parts.push(`| Status | Priority | Task | Owner | Deadline |`);
    parts.push(`|---|---|---|---|---|`);
    meeting.actionItems.forEach(item => {
      const statusIcon = item.status === 'Completed' ? '✅ Done' : item.status === 'In Progress' ? '⏳ In Progress' : '⚪ Pending';
      parts.push(`| ${statusIcon} | **${item.priority}** | ${item.task} | **${item.owner}** | ${item.deadline} |`);
    });
    parts.push('');
  }

  if (meeting.keyTopics && meeting.keyTopics.length > 0) {
    parts.push(`## 💬 Key Discussion Points`);
    meeting.keyTopics.forEach((topic, idx) => {
      parts.push(`### ${idx + 1}. ${topic.topic}`);
      parts.push(topic.summary);
      if (topic.keyPoints && topic.keyPoints.length > 0) {
        topic.keyPoints.forEach(pt => parts.push(`- ${pt}`));
      }
      if (topic.speakersInvolved && topic.speakersInvolved.length > 0) {
        parts.push(`*Speakers involved: ${topic.speakersInvolved.join(', ')}*`);
      }
      parts.push('');
    });
  }

  if (meeting.risksAndBlockers && meeting.risksAndBlockers.length > 0) {
    parts.push(`## ⚠️ Risks & Blockers`);
    meeting.risksAndBlockers.forEach(r => parts.push(`- ${r}`));
    parts.push('');
  }

  if (meeting.openQuestions && meeting.openQuestions.length > 0) {
    parts.push(`## ❓ Open Questions / Follow-ups`);
    meeting.openQuestions.forEach(q => parts.push(`- ${q}`));
    parts.push('');
  }

  if (meeting.transcript && meeting.transcript.length > 0) {
    parts.push(`## 📝 Transcript`);
    meeting.transcript.forEach(t => {
      parts.push(`**${t.speaker}** ${t.timestamp ? `(${t.timestamp})` : ''}: ${t.text}`);
    });
    parts.push('');
  }

  parts.push(`\n---\n*Generated by Voice MoM AI Studio*`);
  return parts.join('\n');
}

export function downloadFile(content: string, fileName: string, contentType: string) {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadAsMarkdown(meeting: MeetingData) {
  const md = generateMarkdownMoM(meeting);
  const safeName = (meeting.title || 'Meeting_MoM').replace(/[^a-zA-Z0-9_-]/g, '_');
  downloadFile(md, `${safeName}_MoM.md`, 'text/markdown;charset=utf-8');
}

export function downloadAsTxt(meeting: MeetingData) {
  const md = generateMarkdownMoM(meeting);
  // Strip markdown ornaments for plain text
  const txt = md
    .replace(/^#{1,6}\s*/gm, '')
    .replace(/\*\*/g, '')
    .replace(/\|/g, ' ')
    .replace(/---+/g, '----');
  const safeName = (meeting.title || 'Meeting_MoM').replace(/[^a-zA-Z0-9_-]/g, '_');
  downloadFile(txt, `${safeName}_MoM.txt`, 'text/plain;charset=utf-8');
}

export function downloadTranscriptTxt(meeting: MeetingData) {
  const lines = (meeting.transcript || []).map((t) => {
    const ts = t.timestamp ? ` [${t.timestamp}]` : '';
    return `${t.speaker || 'Speaker'}${ts}: ${t.text || ''}`;
  });
  const body =
    lines.length > 0
      ? lines.join('\n')
      : 'No transcript available for this meeting.';
  const safeName = (meeting.title || 'Meeting').replace(/[^a-zA-Z0-9_-]/g, '_');
  downloadFile(body, `${safeName}_Transcript.txt`, 'text/plain;charset=utf-8');
}

/**
 * Lightweight DOCX-compatible WordprocessingML package (no external deps).
 * Opens in Microsoft Word / LibreOffice / Google Docs.
 */
export function downloadAsDocx(meeting: MeetingData) {
  const escapeXml = (s: string) =>
    String(s || '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');

  const paragraphs = generateMarkdownMoM(meeting)
    .split('\n')
    .map((line) => {
      const text = escapeXml(line.replace(/^#+\s*/, '').replace(/\*\*/g, ''));
      return `<w:p><w:r><w:t xml:space="preserve">${text || ' '}</w:t></w:r></w:p>`;
    })
    .join('');

  const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    ${paragraphs}
    <w:sectPr/>
  </w:body>
</w:document>`;

  // Minimal single-file "Flat OPC" isn't widely supported; use text/xml Word ML fallback
  // that Word opens, plus .doc.xml extension users can rename — also offer as .docx via Blob type.
  const safeName = (meeting.title || 'Meeting_MoM').replace(/[^a-zA-Z0-9_-]/g, '_');
  downloadFile(
    documentXml,
    `${safeName}_MoM.doc.xml`,
    'application/xml;charset=utf-8',
  );
}

/** Opens print dialog — pair with CSS @media print for PDF. */
export function printAsPdf() {
  window.print();
}

export function downloadAsJSON(meeting: MeetingData) {
  const safeName = (meeting.title || 'Meeting_MoM').replace(/[^a-zA-Z0-9_-]/g, '_');
  downloadFile(JSON.stringify(meeting, null, 2), `${safeName}_Data.json`, 'application/json');
}

export function copyToClipboard(text: string): Promise<void> {
  if (navigator.clipboard && window.isSecureContext) {
    return navigator.clipboard.writeText(text);
  } else {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    return new Promise((resolve, reject) => {
      if (document.execCommand('copy')) {
        resolve();
      } else {
        reject(new Error('Copy failed'));
      }
      textArea.remove();
    });
  }
}
