import { WakeWordItem, VoiceCommandItem, VoiceSystemConfig } from '../types';

export const DEFAULT_WAKE_WORDS: WakeWordItem[] = [
  {
    id: 'ww-namaskar',
    word: 'Namaskar',
    aliases: [
      'namaskar',
      'namaskaar',
      'namaste',
      'namastey',
      'namasthe',
      'नमस्ते',
      'नमस्कार',
      'hello namaskar',
    ],
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    sensitivity: 0.85,
    detectedCount: 0,
    description: 'Traditional greeting wake word in Hindi / Hinglish. Wakes up the assistant and prompts for action.',
  },
  {
    id: 'ww-2click-start',
    word: '2Click Start',
    aliases: [
      '2click start',
      '2 click start',
      'two click start',
      'to click start',
      'too click start',
      'toclick start',
      'tu click start',
      'do click start',
    ],
    language: 'english',
    enabled: true,
    isDefault: true,
    sensitivity: 0.9,
    detectedCount: 0,
    description: 'Primary product wake/trigger phrase to begin a command recording session.',
  },
  {
    id: 'ww-hello',
    word: 'Hello',
    aliases: [
      'hello',
      'hi',
      'hey',
      'hello meeting',
      'hey assistant',
      'hello assistant',
      'हेलो',
    ],
    language: 'english',
    enabled: true,
    isDefault: true,
    sensitivity: 0.85,
    detectedCount: 0,
    description: 'Universal conversational greeting wake word.',
  },
  {
    id: 'ww-mom',
    word: 'Minutes of Meeting',
    aliases: [
      'minutes of meeting',
      'meeting minutes',
      'mom',
      'm o m',
      'minute of meeting',
      'मीटिंग के मिनट्स',
    ],
    language: 'english',
    enabled: true,
    isDefault: true,
    sensitivity: 0.8,
    detectedCount: 0,
    description: 'Direct task-oriented wake phrase.',
  },
  {
    id: 'ww-meeting-start',
    word: 'Meeting Start',
    aliases: [
      'meeting start',
      'start meeting',
      'meeting shuru',
      'shuru karo meeting',
      'मीटिंग शुरू',
      'मीटिंग स्टार्ट',
    ],
    language: 'hinglish',
    enabled: true,
    isDefault: true,
    sensitivity: 0.85,
    detectedCount: 0,
    description: 'Action-oriented wake word to initialize meeting workflows.',
  },
];

export const DEFAULT_VOICE_COMMANDS: VoiceCommandItem[] = [
  {
    id: 'cmd-start-recording',
    phrase: '2Click Start',
    aliases: [
      '2click start',
      '2 click start',
      'two click start',
      'to click start',
      'too click start',
      'toclick start',
      'tu click start',
      'do click start',
      'meeting shuru karo',
      'meeting shuru',
      'start recording',
      'recording start',
      'meeting start',
      'start meeting',
      'record start',
      'recording shuru karo',
      'meeting chalu karo',
      'session start',
      'शुरू करो',
      'मीटिंग शुरू करो',
      'मीटिंग शुरू',
      'रिकॉर्डिंग शुरू करो',
    ],
    action: 'START_RECORDING',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Starts command-based record/transcribe session (hands-free).',
    executionCount: 0,
  },
  {
    id: 'cmd-stop-recording',
    phrase: '2Click Stop',
    aliases: [
      '2click stop',
      '2 click stop',
      'two click stop',
      'to click stop',
      'too click stop',
      'toclick stop',
      'meeting khatam',
      'meeting khatm',
      'stop recording',
      'recording stop',
      'meeting stop',
      'stop meeting',
      'record stop',
      'meeting band karo',
      'recording band karo',
      'session stop',
      'मीटिंग बंद करो',
      'रिकॉर्डिंग बंद करो',
      'मीटिंग खत्म',
    ],
    action: 'STOP_RECORDING',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Stops session, runs Gemini MoM, Instant Saves to user DB.',
    executionCount: 0,
  },
  {
    id: 'cmd-save-note',
    phrase: 'Save note',
    aliases: [
      'save note',
      'save notes',
      'save mom',
      'save minutes',
      'note save karo',
      'सेव नोट',
      'नोट सेव करो',
    ],
    action: 'SAVE_NOTE',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Stops recording and Instant Saves processed note (same as stop+save).',
    executionCount: 0,
  },
  {
    id: 'cmd-cancel-recording',
    phrase: 'Cancel recording',
    aliases: [
      'cancel recording',
      'recording cancel',
      'discard recording',
      'cancel note',
      'recording cancel karo',
      'रद्द करो',
      'कैंसल रिकॉर्डिंग',
      'रिकॉर्डिंग रद्द',
    ],
    action: 'CANCEL_RECORDING',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Clears the session buffer without saving to the database.',
    executionCount: 0,
  },
  {
    id: 'cmd-complete-meeting',
    phrase: 'Meeting Complete',
    aliases: [
      'meeting complete',
      'meeting samapt',
      'meeting finish',
      'finish meeting',
      'complete meeting',
      'khatam karo',
      'मीटिंग समाप्त',
    ],
    action: 'STOP_RECORDING',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Finalizes the meeting recording session.',
    executionCount: 0,
  },
  {
    id: 'cmd-generate-minutes',
    phrase: 'Generate Minutes',
    aliases: [
      'generate minutes',
      'minutes generate karo',
      'generate mom',
      'mom generate karo',
      'minutes banao',
      'mom bana do',
      'ai minutes generate karo',
      'generate summary',
      'मिनट्स बनाओ',
      'एमओएम जनरेट करो',
    ],
    action: 'GENERATE_MINUTES',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Triggers AI Minutes Intelligence synthesis from the recorded transcript.',
    executionCount: 0,
  },
  {
    id: 'cmd-make-minutes',
    phrase: 'Make Minutes',
    aliases: [
      'make minutes',
      'create minutes',
      'create mom',
      'make mom',
      'mom taiyar karo',
      'minutes prepare karo',
      'minutes banao ji',
      'ड्राफ्ट मिनट्स बनाओ',
    ],
    action: 'GENERATE_MINUTES',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Synthesizes executive summary, decisions, and action items.',
    executionCount: 0,
  },
  {
    id: 'cmd-pause-recording',
    phrase: 'Pause Recording',
    aliases: [
      'pause recording',
      'pause meeting',
      'meeting pause karo',
      'thodi der ruko',
      'pause kardo',
      'पॉज़ करो',
    ],
    action: 'PAUSE_RECORDING',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Temporarily pauses microphone audio recording.',
    executionCount: 0,
  },
  {
    id: 'cmd-resume-recording',
    phrase: 'Resume Recording',
    aliases: [
      'resume recording',
      'resume meeting',
      'continue recording',
      'aage badho',
      'shuru rakho',
      'फिर से शुरू करो',
    ],
    action: 'RESUME_RECORDING',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Resumes paused audio recording.',
    executionCount: 0,
  },
  {
    id: 'cmd-open-settings',
    phrase: 'Open Voice Settings',
    aliases: [
      'open settings',
      'voice settings',
      'settings kholo',
      'voice settings open karo',
      'wake word settings',
    ],
    action: 'OPEN_SETTINGS',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Navigates to the voice and wake word configuration panel.',
    executionCount: 0,
  },
  {
    id: 'cmd-open-meetings',
    phrase: 'Open Meetings Hub',
    aliases: [
      'open meetings',
      'go to meetings',
      'meetings hub',
      'meetings dikhao',
      'all meetings',
    ],
    action: 'OPEN_MEETINGS',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Navigates to the primary meetings list dashboard.',
    executionCount: 0,
  },
  {
    id: 'cmd-new-meeting',
    phrase: 'New Meeting',
    aliases: [
      'new meeting',
      'create meeting',
      'nayi meeting',
      'nayee meeting banao',
      'start new session',
    ],
    action: 'NEW_MEETING',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Opens new meeting creation modal/view.',
    executionCount: 0,
  },
];

export const DEFAULT_VOICE_CONFIG: VoiceSystemConfig = {
  wakeWords: DEFAULT_WAKE_WORDS,
  commands: DEFAULT_VOICE_COMMANDS,
  isWakeWordEnabled: true,
  isVoiceCommandEnabled: true,
  languageMode: 'auto',
  continuousListening: true,
  autoStartListening: false,
  audioFeedback: true,
  visualFeedback: true,
  hapticFeedback: true,
  /** Hands-free command session: start/stop/cancel without extra confirm dialog */
  requireExplicitConfirmationForRecording: false,
  commandSessionSaveUrl: '',
};
