import { WakeWordItem, VoiceCommandItem, VoiceSystemConfig } from '../types';

export const DEFAULT_WAKE_WORDS: WakeWordItem[] = [
  {
    id: 'ww-namaskar',
    word: 'Namaskar',
    aliases: [
      'namaskar',
      'namaskaar',
      'namaste',
      'namastey',
      'namasthe',
      'नमस्ते',
      'नमस्कार',
      'hello namaskar',
    ],
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    sensitivity: 0.85,
    detectedCount: 0,
    description: 'Traditional greeting wake word in Hindi / Hinglish. Wakes up the assistant and prompts for action.',
  },
  {
    id: 'ww-hello',
    word: 'Hello',
    aliases: [
      'hello',
      'hi',
      'hey',
      'hello meeting',
      'hey assistant',
      'hello assistant',
      'हेलो',
    ],
    language: 'english',
    enabled: true,
    isDefault: true,
    sensitivity: 0.85,
    detectedCount: 0,
    description: 'Universal conversational greeting wake word.',
  },
  {
    id: 'ww-mom',
    word: 'Minutes of Meeting',
    aliases: [
      'minutes of meeting',
      'meeting minutes',
      'mom',
      'm o m',
      'minute of meeting',
      'मीटिंग के मिनट्स',
    ],
    language: 'english',
    enabled: true,
    isDefault: true,
    sensitivity: 0.8,
    detectedCount: 0,
    description: 'Direct task-oriented wake phrase.',
  },
  {
    id: 'ww-meeting-start',
    word: 'Meeting Start',
    aliases: [
      'meeting start',
      'start meeting',
      'meeting shuru',
      'shuru karo meeting',
      'मीटिंग शुरू',
      'मीटिंग स्टार्ट',
    ],
    language: 'hinglish',
    enabled: true,
    isDefault: true,
    sensitivity: 0.85,
    detectedCount: 0,
    description: 'Action-oriented wake word to initialize meeting workflows.',
  },
];

export const DEFAULT_VOICE_COMMANDS: VoiceCommandItem[] = [
  {
    id: 'cmd-start-recording',
    phrase: 'Meeting Start',
    aliases: [
      'meeting start',
      'start meeting',
      'start recording',
      'record start',
      'meeting shuru karo',
      'recording shuru karo',
      'meeting chalu karo',
      'shuru kijiye',
      'recording on karo',
      'मीटिंग शुरू करो',
      'रिकॉर्डिंग शुरू करो',
    ],
    action: 'START_RECORDING',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Arms or initiates recording in the active studio or recorder with visual consent.',
    executionCount: 0,
  },
  {
    id: 'cmd-stop-recording',
    phrase: 'Meeting Stop',
    aliases: [
      'meeting stop',
      'stop meeting',
      'stop recording',
      'record stop',
      'meeting band karo',
      'recording band karo',
      'meeting roko',
      'roko recording',
      'band kijiye',
      'मीटिंग बंद करो',
      'रिकॉर्डिंग बंद करो',
    ],
    action: 'STOP_RECORDING',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Stops active audio recording session safely.',
    executionCount: 0,
  },
  {
    id: 'cmd-complete-meeting',
    phrase: 'Meeting Complete',
    aliases: [
      'meeting complete',
      'meeting khatam',
      'meeting samapt',
      'meeting finish',
      'finish meeting',
      'complete meeting',
      'khatam karo',
      'मीटिंग खत्म',
      'मीटिंग समाप्त',
    ],
    action: 'STOP_RECORDING',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Finalizes the meeting recording session.',
    executionCount: 0,
  },
  {
    id: 'cmd-generate-minutes',
    phrase: 'Generate Minutes',
    aliases: [
      'generate minutes',
      'minutes generate karo',
      'generate mom',
      'mom generate karo',
      'minutes banao',
      'mom bana do',
      'ai minutes generate karo',
      'generate summary',
      'मिनट्स बनाओ',
      'एमओएम जनरेट करो',
    ],
    action: 'GENERATE_MINUTES',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Triggers AI Minutes Intelligence synthesis from the recorded transcript.',
    executionCount: 0,
  },
  {
    id: 'cmd-make-minutes',
    phrase: 'Make Minutes',
    aliases: [
      'make minutes',
      'create minutes',
      'create mom',
      'make mom',
      'mom taiyar karo',
      'minutes prepare karo',
      'minutes banao ji',
      'ड्राफ्ट मिनट्स बनाओ',
    ],
    action: 'GENERATE_MINUTES',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Synthesizes executive summary, decisions, and action items.',
    executionCount: 0,
  },
  {
    id: 'cmd-pause-recording',
    phrase: 'Pause Recording',
    aliases: [
      'pause recording',
      'pause meeting',
      'meeting pause karo',
      'thodi der ruko',
      'pause kardo',
      'पॉज़ करो',
    ],
    action: 'PAUSE_RECORDING',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Temporarily pauses microphone audio recording.',
    executionCount: 0,
  },
  {
    id: 'cmd-resume-recording',
    phrase: 'Resume Recording',
    aliases: [
      'resume recording',
      'resume meeting',
      'continue recording',
      'aage badho',
      'shuru rakho',
      'फिर से शुरू करो',
    ],
    action: 'RESUME_RECORDING',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Resumes paused audio recording.',
    executionCount: 0,
  },
  {
    id: 'cmd-open-settings',
    phrase: 'Open Voice Settings',
    aliases: [
      'open settings',
      'voice settings',
      'settings kholo',
      'voice settings open karo',
      'wake word settings',
    ],
    action: 'OPEN_SETTINGS',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Navigates to the voice and wake word configuration panel.',
    executionCount: 0,
  },
  {
    id: 'cmd-open-meetings',
    phrase: 'Open Meetings Hub',
    aliases: [
      'open meetings',
      'go to meetings',
      'meetings hub',
      'meetings dikhao',
      'all meetings',
    ],
    action: 'OPEN_MEETINGS',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Navigates to the primary meetings list dashboard.',
    executionCount: 0,
  },
  {
    id: 'cmd-new-meeting',
    phrase: 'New Meeting',
    aliases: [
      'new meeting',
      'create meeting',
      'nayi meeting',
      'nayee meeting banao',
      'start new session',
    ],
    action: 'NEW_MEETING',
    language: 'multilingual',
    enabled: true,
    isDefault: true,
    description: 'Opens new meeting creation modal/view.',
    executionCount: 0,
  },
];

export const DEFAULT_VOICE_CONFIG: VoiceSystemConfig = {
  wakeWords: DEFAULT_WAKE_WORDS,
  commands: DEFAULT_VOICE_COMMANDS,
  isWakeWordEnabled: true,
  isVoiceCommandEnabled: true,
  languageMode: 'auto',
  continuousListening: true,
  audioFeedback: true,
  visualFeedback: true,
  requireExplicitConfirmationForRecording: true,
};
