/**
 * Branded field-visit PDF generator (PDFKit).
 */

import PDFDocument from 'pdfkit';
import fs from 'fs';
import fsp from 'fs/promises';
import path from 'path';
import { enterpriseConfig } from '../config/env.ts';

export interface FieldPdfInput {
  visitId: string;
  title: string;
  domain?: string;
  executiveName?: string;
  siteName?: string;
  latitude?: number;
  longitude?: number;
  arrivedAt?: string;
  departedAt?: string;
  executiveSummary: string;
  actionItems: Array<{ task: string; owner?: string; deadline?: string; priority?: string }>;
  decisions?: string[];
  transcript: string;
}

export interface FieldPdfResult {
  filePath: string;
  fileName: string;
  downloadPath: string;
  bytes: number;
}

export async function generateFieldVisitPdf(input: FieldPdfInput): Promise<FieldPdfResult> {
  const dir = path.resolve(process.cwd(), enterpriseConfig.fieldVisit.pdfStorageDir);
  await fsp.mkdir(dir, { recursive: true });
  const fileName = `FieldVisit_${input.visitId.replace(/[^\w.-]/g, '_')}.pdf`;
  const filePath = path.join(dir, fileName);

  await new Promise<void>((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4', info: { Title: input.title, Author: '2Click MoM' } });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    doc.fillColor('#0f766e').fontSize(20).text('2Click MoM — Field Visit Report', { align: 'left' });
    doc.moveDown(0.3);
    doc.fillColor('#334155').fontSize(10).text('AI-Powered Field Workforce & Voice Minutes');
    doc.moveDown();
    doc.fillColor('#0f172a').fontSize(14).text(input.title);
    doc.fontSize(10).fillColor('#475569');
    doc.text(`Visit ID: ${input.visitId}`);
    if (input.domain) doc.text(`Domain: ${input.domain}`);
    if (input.executiveName) doc.text(`Executive: ${input.executiveName}`);
    if (input.siteName) doc.text(`Site: ${input.siteName}`);
    if (input.latitude != null && input.longitude != null) {
      doc.text(`Geo: ${input.latitude.toFixed(5)}, ${input.longitude.toFixed(5)}`);
    }
    if (input.arrivedAt) doc.text(`Arrived: ${input.arrivedAt}`);
    if (input.departedAt) doc.text(`Departed: ${input.departedAt}`);
    doc.moveDown();

    doc.fillColor('#0f766e').fontSize(12).text('Executive Summary');
    doc.moveDown(0.3);
    doc.fillColor('#0f172a').fontSize(10).text(input.executiveSummary || '—', { align: 'left' });
    doc.moveDown();

    if (input.decisions?.length) {
      doc.fillColor('#0f766e').fontSize(12).text('Decisions');
      doc.moveDown(0.3);
      doc.fillColor('#0f172a').fontSize(10);
      input.decisions.forEach((d, i) => doc.text(`${i + 1}. ${d}`));
      doc.moveDown();
    }

    doc.fillColor('#0f766e').fontSize(12).text('Action Items');
    doc.moveDown(0.3);
    doc.fillColor('#0f172a').fontSize(10);
    if (!input.actionItems?.length) {
      doc.text('None');
    } else {
      input.actionItems.forEach((a, i) => {
        doc.text(
          `${i + 1}. ${a.task} — Owner: ${a.owner || 'N/A'} · Due: ${a.deadline || 'N/A'} · ${a.priority || 'Medium'}`,
        );
      });
    }
    doc.moveDown();

    doc.fillColor('#0f766e').fontSize(12).text('Business Transcript (verbatim, privacy-filtered)');
    doc.moveDown(0.3);
    doc.fillColor('#0f172a').fontSize(9).text(input.transcript || '—', { align: 'left' });

    doc.moveDown(2);
    doc.fontSize(8).fillColor('#94a3b8').text('Generated by 2Click Voice MoM · Confidential', { align: 'center' });

    doc.end();
    stream.on('finish', () => resolve());
    stream.on('error', reject);
  });

  const st = await fsp.stat(filePath);
  return {
    filePath,
    fileName,
    downloadPath: `/api/field/pdfs/${fileName}`,
    bytes: st.size,
  };
}
