/** Home page copy — pure English OR pure Hindi per selected language */

export const HOME_COPY = {
  en: {
    seoTitle: "2click.in — Construction Store, BOQ Calculator, Tenders, Solar & ERP",
    seoDesc: "India's construction super-app — brand-wise material store, full home BOQ builder, interior calculators, enrollment, tender bidding, solar EPC and Mera Ghar ERP on one login.",
    badge: "Enterprise Construction OS",
    heroTitle: "Build. Bid. Procure.",
    heroTitleAccent: "All in one platform.",
    heroSub: "SaaS, ERP, marketing, solar, tender bidding and marketplace — everything on one login. The complete operating system for India's construction economy.",
    ctaStart: "Start free",
    ctaTenders: "View live tenders",
    waMsg: "Hello 2click.in — I would like to know more about the construction platform.",
    waLabel: "WhatsApp",
    modulesTitle: "One platform. Eight verticals.",
    modulesSub: "Every workflow your construction business needs — modular, integrated, enterprise-grade.",
    modules: [
      { title: "Tender & Reverse Auction", desc: "Publish tenders, run live reverse auctions with auto-ranking and AI bid evaluation." },
      { title: "B2B/B2C Marketplace", desc: "Multi-vendor procurement of steel, cement, solar and more with GST invoicing." },
      { title: "Solar Energy Portal", desc: "Capacity and ROI calculators, subsidy estimation and instant quotations." },
      { title: "Construction ERP + Mera Ghar", desc: "From blueprint to housewarming — BOQ, agreement, layout unlock and milestone payments." },
      { title: "AI Platform", desc: "AI assistant, tender summarization, cost estimation and recommendations." },
      { title: "RBAC & Admin", desc: "Unlimited roles, granular permissions and enterprise audit logging." },
    ],
    stats: [
      { k: "₹2,400 Cr+", v: "Tender value processed" },
      { k: "48,000+", v: "SKUs in marketplace" },
      { k: "12,500+", v: "Verified vendors" },
    ],
    leadTag: "Get started",
    leadTitle: "Start today",
    leadSub: "Are you a vendor? List your shop online. Need a solar quote? Open the calculator.",
    leadVendor: "Become a vendor",
    leadSolar: "Solar calculator",
    bottomTitle: "Ready to digitize your construction business?",
    bottomSub: "Join thousands of vendors, contractors and buyers already on 2click.in.",
    bottomCta: "Create your account",
    quickStore: "Store",
    quickMart: "Super Mart",
    quickBoq: "Full BOQ",
    quickEnroll: "Enrollment",
    ownerTitle: "Site owner / Super Admin",
    ownerSub: "Manage branding, pincodes, users and full platform settings.",
    ownerCta: "Owner secure login",
    ownerHint: "Use /sys/console — not the regular login page.",
  },
  hi: {
    seoTitle: "2click.in — कंस्ट्रक्शन स्टोर, BOQ, टेंडर, सोलर और ERP",
    seoDesc: "भारत का निर्माण सुपर ऐप — ब्रांड-वार स्टोर, पूरा घर BOQ, इंटीरियर कैलकुलेटर, पंजीकरण, टेंडर, सोलर और मेरा घर ERP एक लॉगिन पर।",
    badge: "एंटरप्राइज निर्माण प्लेटफ़ॉर्म",
    heroTitle: "बनाएँ। बोली लगाएँ। खरीदें।",
    heroTitleAccent: "सब एक ही प्लेटफ़ॉर्म पर।",
    heroSub: "सॉफ्टवेयर, ईआरपी, मार्केटिंग, सोलर, टेंडर बिडिंग और मार्केटप्लेस — सब एक ही लॉगिन पर। भारत की निर्माण अर्थव्यवस्था के लिए पूरा संचालन तंत्र।",
    ctaStart: "मुफ़्त शुरू करें",
    ctaTenders: "लाइव टेंडर देखें",
    waMsg: "नमस्ते 2click.in — मुझे निर्माण प्लेटफ़ॉर्म के बारे में जानकारी चाहिए।",
    waLabel: "व्हाट्सऐप",
    modulesTitle: "एक प्लेटफ़ॉर्म। आठ क्षेत्र।",
    modulesSub: "आपके निर्माण व्यवसाय के लिए हर कार्यप्रवाह — मॉड्यूलर, एकीकृत, एंटरप्राइज स्तर पर।",
    modules: [
      { title: "टेंडर और रिवर्स ऑक्शन", desc: "टेंडर प्रकाशित करें, लाइव रिवर्स ऑक्शन चलाएँ, स्वचालित रैंकिंग और एआई बिड मूल्यांकन।" },
      { title: "बीटूबी और बीटूसी मार्केटप्लेस", desc: "स्टील, सीमेंट, सोलर आदि की मल्टी-विक्रेता खरीद, जीएसटी इनवॉइसिंग के साथ।" },
      { title: "सोलर ऊर्जा पोर्टल", desc: "क्षमता और आरओआई कैलकुलेटर, सब्सिडी अनुमान और तुरंत कोटेशन।" },
      { title: "निर्माण ईआरपी + मेरा घर", desc: "नक्शे से गृह प्रवेश तक — बीओक्यू, समझौता, लेआउट अनलॉक और माइलस्टोन भुगतान।" },
      { title: "एआई प्लेटफ़ॉर्म", desc: "एआई सहायक, टेंडर सारांश, लागत अनुमान और सिफारिशें।" },
      { title: "भूमिका प्रबंधन और एडमिन", desc: "असीमित भूमिकाएँ, सूक्ष्म अनुमतियाँ और एंटरप्राइज ऑडिट लॉग।" },
    ],
    stats: [
      { k: "₹2,400 करोड़+", v: "टेंडर मूल्य संसाधित" },
      { k: "48,000+", v: "मार्केटप्लेस में उत्पाद" },
      { k: "12,500+", v: "सत्यापित विक्रेता" },
    ],
    leadTag: "शुरू करें",
    leadTitle: "आज ही शुरू करें",
    leadSub: "विक्रेता हैं? अपनी दुकान ऑनलाइन लगाएँ। सोलर कोट चाहिए? कैलकुलेटर खोलें।",
    leadVendor: "विक्रेता बनें",
    leadSolar: "सोलर कैलकुलेटर",
    bottomTitle: "अपना निर्माण व्यवसाय डिजिटल बनाने के लिए तैयार हैं?",
    bottomSub: "हज़ारों विक्रेता, ठेकेदार और खरीदार पहले से 2click.in पर हैं।",
    bottomCta: "अपना खाता बनाएँ",
    quickStore: "स्टोर",
    quickMart: "सुपर मार्ट",
    quickBoq: "पूरा BOQ",
    quickEnroll: "पंजीकरण",
    ownerTitle: "साइट मालिक / सुपर एडमिन",
    ownerSub: "ब्रांडिंग, पिनकोड, यूज़र और पूरे प्लेटफ़ॉर्म की सेटिंग प्रबंधित करें।",
    ownerCta: "मालिक सुरक्षित लॉगिन",
    ownerHint: "/sys/console उपयोग करें — सामान्य लॉगिन पेज नहीं।",
  },
};

export const REGIONAL_UI = {
  en: {
    inYourArea: "In your area",
    pickLocation: "Pick your location — local highlights appear below",
    state: "State",
    city: "City",
    pincode: "Pincode",
    fallbackHeadline: "Key features for your city",
    findFreelancers: "Find local freelancers",
    getStarted: "Get started",
  },
  hi: {
    inYourArea: "आपके इलाके में",
    pickLocation: "अपना स्थान चुनें — नीचे स्थानीय विशेषताएँ दिखेंगी",
    state: "राज्य",
    city: "शहर",
    pincode: "पिनकोड",
    fallbackHeadline: "आपके शहर की मुख्य सुविधाएँ",
    findFreelancers: "पास के फ्रीलांसर देखें",
    getStarted: "मुफ़्त शुरू करें",
  },
};

export const NAV_COPY = {
  en: {
    more: "More",
    explore: "Explore",
    menu: "Menu",
    login: "Log in",
    join: "Join",
    authCta: "Login / Join",
    authCtaShort: "Account",
    dashboard: "Dashboard",
    langSwitch: "हि",
  },
  hi: {
    more: "और",
    explore: "और देखें",
    menu: "मेनू",
    login: "लॉग इन",
    join: "रजिस्टर",
    authCta: "लॉग इन / रजिस्टर",
    authCtaShort: "खाता",
    dashboard: "डैशबोर्ड",
    langSwitch: "EN",
  },
};
