/**
 * Complete buildecogroup.com functional reference — work types, options, and module catalog.
 * Used by /platform for the master "how it works" guide.
 */

import { FALLBACK_USER_TYPES } from "@/lib/userTypes";
import { USER_PERSONAS, PROPERTY_SUBTYPES, QUALITY_TIERS, NAV_CAPABILITY_MAP } from "@/lib/platformArchitecture";
import { LOGIN_PROFILES } from "@/lib/loginProfiles";

/** High-level types of work the platform supports */
export const WORK_TYPES = [
  {
    id: "new_construction",
    en: "New home & building construction",
    hi: "नया घर और बिल्डिंग निर्माण",
    paths: ["/build", "/estimate", "/projects", "/boq-builder"],
    optionsEn: "Residential · Commercial · Industrial · Villa · Township",
    optionsHi: "आवासीय · व्यावसायिक · औद्योगिक · विला · टाउनशिप",
  },
  {
    id: "renovation",
    en: "Renovation & interior finishing",
    hi: "रेनोवेशन और इंटीरियर फिनिशिंग",
    paths: ["/interior-boq", "/design", "/build"],
    optionsEn: "Tiles · False ceiling · PVC · Paint · Décor · Fabrication",
    optionsHi: "टाइल्स · फॉल्स सीलिंग · PVC · पेंट · डेकोर · फैब्रिकेशन",
  },
  {
    id: "material_procurement",
    en: "Material procurement & e-commerce",
    hi: "सामग्री खरीद और ई-कॉमर्स",
    paths: ["/store", "/mart", "/cart", "/marketplace"],
    optionsEn: "Cement · Steel · Tiles · Paint · Live rates · My bag · BOQ add",
    optionsHi: "सीमेंट · स्टील · टाइल्स · पेंट · लाइव रेट · बैग · BOQ",
  },
  {
    id: "boq_engineering",
    en: "BOQ & cost engineering",
    hi: "BOQ और लागत इंजीनियरिंग",
    paths: ["/boq-builder", "/interior-boq", "/estimate", "/material-calculator"],
    optionsEn: "Full home 13-store BOQ · Category calculators · PDF/Excel export",
    optionsHi: "13-स्टोर BOQ · श्रेणी कैलकुलेटर · PDF/Excel",
  },
  {
    id: "design_3d",
    en: "AI design & 3D studio",
    hi: "AI डिज़ाइन और 3D स्टूडियो",
    paths: ["/design", "/technology"],
    optionsEn: "Floor plan · Elevation · Interior concept · 5-phase 3D workflow",
    optionsHi: "फ्लोर प्लान · एलिवेशन · इंटीरियर · 5-चरण 3D",
  },
  {
    id: "solar_epc",
    en: "Solar EPC & rooftop",
    hi: "सोलर EPC और रूफटॉप",
    paths: ["/solar"],
    optionsEn: "Residential/Commercial · Subsidy · EMI · DPR · WhatsApp quote",
    optionsHi: "आवासीय/व्यावसायिक · सब्सिडी · EMI · DPR · WhatsApp",
  },
  {
    id: "tender_bidding",
    en: "Tenders & vendor bidding",
    hi: "टेंडर और विक्रेता बोली",
    paths: ["/tenders", "/upcoming-projects"],
    optionsEn: "Post tender · Live bids · Reverse auction · EMD tracking",
    optionsHi: "टेंडर पोस्ट · लाइव बोली · रिवर्स ऑक्शन",
  },
  {
    id: "property_advisory",
    en: "Property advisory & legal",
    hi: "प्रॉपर्टी सलाह और कानूनी",
    paths: ["/property-advisory"],
    optionsEn: "Persona match · Plot/building guidance · Consultant connect",
    optionsHi: "पहचान मिलान · प्लॉट/बिल्डिंग गाइड · सलाहकार",
  },
  {
    id: "professionals",
    en: "Hire professionals",
    hi: "पेशेवर हायर करें",
    paths: ["/professionals", "/consultants", "/freelancers"],
    optionsEn: "Architect · Contractor · Interior · Solar · Vendor enroll",
    optionsHi: "वास्तुकार · ठेकेदार · इंटीरियर · सोलर · विक्रेता",
  },
  {
    id: "equipment",
    en: "Equipment rental & logistics",
    hi: "उपकरण रेंटल और लॉजिस्टिक्स",
    paths: ["/equipment-rental"],
    optionsEn: "JCB · Crane · Tipper · Generator · Book/enquire",
    optionsHi: "JCB · क्रेन · टिपर · जनरेटर · बुक",
  },
  {
    id: "onboarding",
    en: "Vendor & user onboarding",
    hi: "विक्रेता और उपयोगकर्ता ऑनबोर्डिंग",
    paths: ["/enroll", "/become-vendor", "/register"],
    optionsEn: "User · Vendor · Shop · KYC · Agreements",
    optionsHi: "यूज़र · विक्रेता · दुकान · KYC · समझौते",
  },
];

/** Every major function: route, who uses it, key options, click flow */
export const FUNCTION_CATALOG = [
  {
    categoryEn: "Start & plan",
    categoryHi: "शुरू और योजना",
    items: [
      {
        id: "build",
        path: "/build",
        nameEn: "2-Click Builder",
        nameHi: "2-क्लिक बिल्डर",
        forEn: "Home owners, developers, contractors",
        forHi: "गृहस्वामी, डेवलपर, ठेकेदार",
        optionsEn: "6 project types → persona → property type → location → quality → dashboard",
        optionsHi: "6 प्रकार → पहचान → प्रॉपर्टी → लोकेशन → गुणवत्ता → डैशबोर्ड",
        clicksEn: "Select card → Next click 2 → profile & area → Open AI dashboard",
        clicksHi: "कार्ड चुनें → क्लिक 2 → प्रोफ़ाइल और एरिया → AI डैशबोर्ड",
      },
      {
        id: "estimate",
        path: "/estimate",
        nameEn: "Cost calculator",
        nameHi: "लागत कैलकुलेटर",
        forEn: "Anyone needing instant build cost",
        forHi: "तुरंत निर्माण लागत",
        optionsEn: "Pincode/GPS · Plot/built-up sqft · Floors/BHK · Quality tier · Solar checkbox",
        optionsHi: "पिनकोड/GPS · क्षेत्रफल · फ्लोर/BHK · गुणवत्ता · सोलर",
        clicksEn: "Enter location & area → Calculate estimate → Download quotation",
        clicksHi: "लोकेशन और एरिया → अनुमान → कोटेशन डाउनलोड",
      },
      {
        id: "projects",
        path: "/projects",
        nameEn: "AI project dashboard",
        nameHi: "AI प्रोजेक्ट डैशबोर्ड",
        forEn: "After 2-click setup",
        forHi: "2-क्लिक के बाद",
        optionsEn: "Material/cost tab · AI 3D studio tab · Generate project plan",
        optionsHi: "मटेरियल/लागत · AI 3D · योजना जनरेट",
        clicksEn: "Review scope → Generate plan → Track BOQ & milestones",
        clicksHi: "स्कोप देखें → योजना जनरेट → BOQ और माइलस्टोन",
      },
    ],
  },
  {
    categoryEn: "BOQ & materials",
    categoryHi: "BOQ और सामग्री",
    items: [
      {
        id: "boq-builder",
        path: "/boq-builder",
        nameEn: "Full home BOQ builder",
        nameHi: "पूरा घर BOQ",
        forEn: "Contractors, owners, procurement",
        forHi: "ठेकेदार, मालिक, खरीद",
        optionsEn: "13 category stores · Select all/clear · Brand pick · PDF export",
        optionsHi: "13 स्टोर · सभी चुनें · ब्रांड · PDF",
        clicksEn: "Pick stores → Add items per store → Generate BOQ → Print/share",
        clicksHi: "स्टोर चुनें → आइटम जोड़ें → BOQ → प्रिंट/शेयर",
      },
      {
        id: "interior-boq",
        path: "/interior-boq",
        nameEn: "Interior BOQ calculators",
        nameHi: "इंटीरियर BOQ",
        forEn: "Interior trades, homeowners",
        forHi: "इंटीरियर, गृहस्वामी",
        optionsEn: "Décor · Tiles · Ceiling · PVC · Renovation · Gardening · Vastu · Fabrication",
        optionsHi: "डेकोर · टाइल्स · सीलिंग · PVC · रेनोवेशन · वास्तु · फैब्रिकेशन",
        clicksEn: "Open catalog card → Pick brand/design → Enter dimensions → Itemized cost",
        clicksHi: "कैटलॉग → ब्रांड → आयाम → आइटम लागत",
      },
      {
        id: "material-calc",
        path: "/material-calculator",
        nameEn: "Hindi material calculator",
        nameHi: "हिंदी सामग्री कैलकुलेटर",
        forEn: "Site supervisors, quick estimates",
        forHi: "साइट सुपरवाइज़र",
        optionsEn: "Cement · Steel · Bricks · Sand · Tiles · Paint from sqft",
        optionsHi: "सीमेंट · स्टील · ईंट · रेत · टाइल्स · पेंट",
        clicksEn: "Built-up sqft → material breakdown",
        clicksHi: "बिल्ट-अप → सामग्री ब्रेकडाउन",
      },
      {
        id: "store",
        path: "/store",
        nameEn: "Construction store",
        nameHi: "कंस्ट्रक्शन स्टोर",
        forEn: "Buyers, contractors",
        forHi: "खरीदार, ठेकेदार",
        optionsEn: "Search · Category filter · LIVE RATE · My bag · Full BOQ link",
        optionsHi: "खोज · श्रेणी · लाइव रेट · बैग · BOQ",
        clicksEn: "Browse → Add to bag → Checkout cart",
        clicksHi: "ब्राउज़ → बैग में → चेकआउट",
      },
      {
        id: "mart",
        path: "/mart",
        nameEn: "Super Mart (live rates)",
        nameHi: "सुपर मार्ट",
        forEn: "Contractors comparing market rates",
        forHi: "मार्केट रेट तुलना",
        optionsEn: "82+ materials · Trend charts · Buy timing notes",
        optionsHi: "82+ सामग्री · ट्रेंड चार्ट",
        clicksEn: "Filter category → View trend → Add to BOQ",
        clicksHi: "श्रेणी → ट्रेंड → BOQ में",
      },
    ],
  },
  {
    categoryEn: "Design & technology",
    categoryHi: "डिज़ाइन और टेक्नोलॉजी",
    items: [
      {
        id: "design",
        path: "/design",
        nameEn: "AI design studio",
        nameHi: "AI डिज़ाइन स्टूडियो",
        forEn: "Architects, owners visualizing space",
        forHi: "वास्तुकार, मालिक",
        optionsEn: "Floor plan · Elevation · Interior · Colour · Style · Room prompt",
        optionsHi: "फ्लोर प्लान · एलिवेशन · इंटीरियर · रंग · स्टाइल",
        clicksEn: "Pick module → Enter prompt → Generate design workflow",
        clicksHi: "मॉड्यूल → प्रॉम्प्ट → डिज़ाइन जनरेट",
      },
      {
        id: "technology",
        path: "/technology",
        nameEn: "LiDAR · 3D · VR",
        nameHi: "LiDAR · 3D · VR",
        forEn: "Site capture, walkthroughs",
        forHi: "साइट कैप्चर, वॉकथ्रू",
        optionsEn: "LiDAR scan · 3D models · VR preview · Site-mapping CTA",
        optionsHi: "LiDAR · 3D · VR · साइट-मैपिंग",
        clicksEn: "Start project → Design studio → Digital site map",
        clicksHi: "प्रोजेक्ट → डिज़ाइन स्टूडियो → साइट मैप",
      },
    ],
  },
  {
    categoryEn: "Solar & energy",
    categoryHi: "सोलर और ऊर्जा",
    items: [
      {
        id: "solar",
        path: "/solar",
        nameEn: "Solar EPC calculator",
        nameHi: "सोलर EPC",
        forEn: "Homeowners, commercial rooftops",
        forHi: "घर, व्यावसायिक छत",
        optionsEn: "Residential/Commercial · On-grid/Hybrid · Tier brands · Subsidy · EMI · DPR",
        optionsHi: "आवासीय/व्यावसायिक · ऑन-ग्रिड · ब्रांड · सब्सिडी · EMI · DPR",
        clicksEn: "Configure → Generate estimate → WhatsApp quote · Save proposal",
        clicksHi: "कॉन्फ़िगर → अनुमान → WhatsApp कोट · सेव",
      },
    ],
  },
  {
    categoryEn: "Marketplace & tenders",
    categoryHi: "मार्केटप्लेस और टेंडर",
    items: [
      {
        id: "tenders",
        path: "/tenders",
        nameEn: "Tender hub",
        nameHi: "टेंडर हब",
        forEn: "Owners posting work, vendors bidding",
        forHi: "मालिक पोस्ट, विक्रेता बोली",
        optionsEn: "Publish tender · Place bid · Track status · EMD",
        optionsHi: "टेंडर पब्लिश · बोली · स्थिति · EMD",
        clicksEn: "Browse tender → View detail → Submit bid",
        clicksHi: "टेंडर देखें → विवरण → बोली भेजें",
      },
      {
        id: "upcoming",
        path: "/upcoming-projects",
        nameEn: "Upcoming projects",
        nameHi: "आगामी प्रोजेक्ट",
        forEn: "Vendors finding new work",
        forHi: "विक्रेता नए काम",
        optionsEn: "Location filters · Project cards → Tender link",
        optionsHi: "लोकेशन फ़िल्टर · कार्ड → टेंडर",
        clicksEn: "Filter region → Open project → Bid",
        clicksHi: "क्षेत्र → प्रोजेक्ट → बोली",
      },
      {
        id: "marketplace",
        path: "/marketplace",
        nameEn: "B2B marketplace",
        nameHi: "B2B मार्केटप्लेस",
        forEn: "Material buyers",
        forHi: "सामग्री खरीदार",
        optionsEn: "Product grid · Vendor listings · Cart",
        optionsHi: "उत्पाद · विक्रेता · कार्ट",
        clicksEn: "Browse → Add to cart → Order",
        clicksHi: "ब्राउज़ → कार्ट → ऑर्डर",
      },
    ],
  },
  {
    categoryEn: "Advisory & rental",
    categoryHi: "सलाह और रेंटल",
    items: [
      {
        id: "advisory",
        path: "/property-advisory",
        nameEn: "Property advisory",
        nameHi: "प्रॉपर्टी सलाह",
        forEn: "Buyers, investors, developers",
        forHi: "खरीदार, निवेशक",
        optionsEn: "4-step wizard · Persona · Property type · Advisor match",
        optionsHi: "4-चरण · पहचान · प्रकार · सलाहकार",
        clicksEn: "Type → Location → Details → Matched consultants",
        clicksHi: "प्रकार → लोकेशन → विवरण → सलाहकार",
      },
      {
        id: "equipment",
        path: "/equipment-rental",
        nameEn: "Equipment rental",
        nameHi: "उपकरण रेंटल",
        forEn: "Site managers, contractors",
        forHi: "साइट मैनेजर",
        optionsEn: "JCB · Crane · Concrete · Tipper · State/city filter",
        optionsHi: "JCB · क्रेन · टिपर · राज्य/शहर",
        clicksEn: "Filter → Card → Book or enquire",
        clicksHi: "फ़िल्टर → कार्ड → बुक/पूछताछ",
      },
    ],
  },
  {
    categoryEn: "People & accounts",
    categoryHi: "लोग और खाते",
    items: [
      {
        id: "professionals",
        path: "/professionals",
        nameEn: "Professionals hub",
        nameHi: "पेशेवर हब",
        forEn: "Finding or joining as pro",
        forHi: "पेशेवर खोज या जॉइन",
        optionsEn: "Architect · Contractor · Interior · Solar · Vendor · Join",
        optionsHi: "वास्तुकार · ठेकेदार · इंटीरियर · सोलर · विक्रेता",
        clicksEn: "Portal card → Profiles or enrollment",
        clicksHi: "पोर्टल → प्रोफ़ाइल या पंजीकरण",
      },
      {
        id: "freelancers",
        path: "/freelancers",
        nameEn: "Freelancer directory",
        nameHi: "फ्रीलांसर निर्देशिका",
        forEn: "Hiring talent",
        forHi: "टैलेंट हायर",
        optionsEn: "Search skill/city · Contact · Enquiry · Agreements",
        optionsHi: "स्किल/शहर खोज · संपर्क · enquiry",
        clicksEn: "Search → Profile card → Send enquiry",
        clicksHi: "खोज → प्रोफ़ाइल → enquiry",
      },
      {
        id: "consultants",
        path: "/consultants",
        nameEn: "Consultant directory",
        nameHi: "कंसल्टेंट निर्देशिका",
        forEn: "Architect/engineer hire",
        forHi: "वास्तुकार/इंजीनियर",
        optionsEn: "Category · Rating · Portfolio · Book consult",
        optionsHi: "श्रेणी · रेटिंग · पोर्टफोलियो",
        clicksEn: "Filter → Profile → Request callback",
        clicksHi: "फ़िल्टर → प्रोफ़ाइल → कॉलबैक",
      },
      {
        id: "enroll",
        path: "/enroll",
        nameEn: "Enrollment wizard",
        nameHi: "पंजीकरण विज़ार्ड",
        forEn: "New users, vendors, shops",
        forHi: "नए यूज़र, विक्रेता, दुकान",
        optionsEn: "User/Vendor/Shop · Categories · KYC · Agreements",
        optionsHi: "यूज़र/विक्रेता/दुकान · श्रेणी · KYC",
        clicksEn: "4 steps → Dashboard by role",
        clicksHi: "4 चरण → रोल डैशबोर्ड",
      },
      {
        id: "login",
        path: "/login",
        nameEn: "Login",
        nameHi: "लॉग इन",
        forEn: "All roles",
        forHi: "सभी रोल",
        optionsEn: "Customer · Vendor · Contractor · Architect demos",
        optionsHi: "ग्राहक · विक्रेता · ठेकेदार · वास्तुकार डेमो",
        clicksEn: "Role → Email/password → Dashboard (/sys/console for admin)",
        clicksHi: "रोल → ईमेल/पासवर्ड → डैशबोर्ड",
      },
    ],
  },
];

/** Build wizard & estimator option lists */
export const PLATFORM_OPTIONS = {
  projectTypes: [
    { id: "residential", en: "Residential", hi: "आवासीय" },
    { id: "commercial", en: "Commercial", hi: "व्यावसायिक" },
    { id: "industrial", en: "Industrial", hi: "औद्योगिक" },
    { id: "renovation", en: "Renovation", hi: "रेनोवेशन" },
    { id: "interior", en: "Interior", hi: "इंटीरियर" },
    { id: "solar", en: "Solar", hi: "सोलर" },
  ],
  personas: USER_PERSONAS.map((p) => ({ id: p.id, en: p.en, hi: p.hi })),
  propertySubtypes: PROPERTY_SUBTYPES.map((p) => ({ id: p.id, en: p.en, hi: p.hi })),
  qualityTiers: QUALITY_TIERS.map((q) => ({
    id: q.id,
    en: q.labelEn,
    hi: q.labelHi,
    rate: q.rate,
  })),
  estimateQualities: [
    { id: "low", en: "Low", hi: "कम" },
    { id: "standard", en: "Standard", hi: "स्टैंडर्ड" },
    { id: "premium", en: "Premium", hi: "प्रीमियम" },
    { id: "luxury", en: "Luxury", hi: "लक्ज़री" },
  ],
  enrollmentUserTypes: FALLBACK_USER_TYPES.map((u) => ({
    code: u.code,
    en: u.label,
    hi: u.label,
    categories: u.category_types,
  })),
  loginProfiles: LOGIN_PROFILES.filter((p) => p.id !== "admin").map((p) => ({
    id: p.id,
    en: p.label,
    hi: p.labelHi,
    dashboard: p.dashboard,
  })),
};

/** Dashboard destination per login role */
export const DASHBOARD_BY_ROLE = [
  { roleEn: "Customer", roleHi: "ग्राहक", path: "/dashboard", panelEn: "Customer dashboard — Mera Ghar, cart, tenders, solar", panelHi: "ग्राहक डैशबोर्ड — मेरा घर, कार्ट, टेंडर" },
  { roleEn: "Vendor", roleHi: "विक्रेता", path: "/dashboard", panelEn: "Vendor portal — products, orders, RFQ inbox, tenders", panelHi: "विक्रेता — उत्पाद, ऑर्डर, RFQ" },
  { roleEn: "Contractor", roleHi: "ठेकेदार", path: "/dashboard", panelEn: "Contractor workspace — BOQ, DPR, client projects", panelHi: "ठेकेदार — BOQ, DPR, प्रोजेक्ट" },
  { roleEn: "Architect / Freelancer", roleHi: "वास्तुकार / फ्रीलांसर", path: "/dashboard", panelEn: "Freelancer/consultant workspace — enquiries, studio", panelHi: "फ्रीलांसर वर्कस्पेस — enquiry, स्टूडियो" },
  { roleEn: "Super admin", roleHi: "सुपर एडमिन", path: "/sys/console", panelEn: "Admin console — RBAC, geo, rates, users (not /login)", panelHi: "एडमिन कंसोल — RBAC, geo, रेट (/login नहीं)" },
];

export const NAV_QUICK_MAP = NAV_CAPABILITY_MAP;
