/** Super-app product copy — English / Hindi */

export const SUPER_COPY = {
  en: {
    tagline: "From land to complete home — in just 2 clicks",
    taglineHiShort: "ज़मीन से संपूर्ण घर — मात्र 2 क्लिक में",
    heroTitle: "India's AI Construction Super App",
    heroSub: "Construction, interior, solar, design, materials, professionals and project tracking — one premium platform.",
    ctaStartProject: "Start my project",
    ctaFreeEstimate: "Get free estimate",
    servicesTitle: "Everything you need to build",
    servicesSub: "One screen. No endless scrolling.",
    trustTitle: "Built for trust & transparency",
    techTitle: "Powered by modern technology",
    twoClickTitle: "The real 2-click experience",
    twoClickSub: "Click 1: what to build. Click 2: project details. Then your AI project dashboard opens.",
    plannerTitle: "AI Project Dashboard",
    estimateTitle: "Cost calculator",
    generatePlan: "Generate my project plan",
    downloadPdf: "Download quotation PDF",
    qualityLow: "Low",
    qualityStandard: "Standard",
    qualityPremium: "Premium",
    qualityLuxury: "Luxury",
    comingSoon: "Coming soon",
    loginForAi: "Log in to chat with 2Click AI",
    nav: {
      home: "Home",
      build: "Build",
      estimate: "Estimate",
      design: "Design",
      materials: "Materials",
      professionals: "Professionals",
      solar: "Solar",
      projects: "Projects",
      about: "About",
      ai: "AI",
      profile: "Profile",
      services: "Services",
    },
    projectTypes: [
      { id: "residential", en: "Residential", hi: "आवासीय" },
      { id: "commercial", en: "Commercial", hi: "व्यावसायिक" },
      { id: "industrial", en: "Industrial", hi: "औद्योगिक" },
      { id: "renovation", en: "Renovation", hi: "नवीनीकरण" },
      { id: "interior", en: "Interior", hi: "इंटीरियर" },
      { id: "solar", en: "Solar", hi: "सोलर" },
    ],
    services: [
      { id: "construction", en: "Construction", hi: "निर्माण", to: "/build" },
      { id: "architecture", en: "Architecture", hi: "वास्तुकला", to: "/consultants" },
      { id: "interior", en: "Interior", hi: "इंटीरियर", to: "/interior-boq" },
      { id: "solar", en: "Solar", hi: "सोलर", to: "/solar" },
      { id: "lidar", en: "LiDAR Survey", hi: "LiDAR सर्वे", to: "/technology" },
      { id: "vr", en: "3D / VR", hi: "3D / VR", to: "/technology" },
      { id: "materials", en: "Materials", hi: "सामग्री", to: "/store" },
      { id: "labour", en: "Labour", hi: "श्रम", to: "/freelancers" },
      { id: "contractor", en: "Contractor", hi: "ठेकेदार", to: "/freelancers" },
      { id: "pm", en: "Project Mgmt", hi: "प्रोजेक्ट", to: "/projects" },
    ],
    trust: [
      { en: "Verified professionals", hi: "सत्यापित पेशेवर" },
      { en: "Transparent pricing", hi: "पारदर्शी मूल्य" },
      { en: "Digital quotations", hi: "डिजिटल कोटेशन" },
      { en: "Project tracking", hi: "प्रोजेक्ट ट्रैकिंग" },
      { en: "Document vault", hi: "दस्तावेज़ वॉल्ट" },
      { en: "Secure payments", hi: "सुरक्षित भुगतान" },
    ],
    tech: [
      { en: "AI planning", hi: "AI योजना" },
      { en: "LiDAR ready", hi: "LiDAR तैयार" },
      { en: "3D walkthrough", hi: "3D वॉकथ्रू" },
      { en: "VR preview", hi: "VR पूर्वावलोकन" },
    ],
  },
  hi: {
    tagline: "ज़मीन से संपूर्ण घर — मात्र 2 क्लिक में",
    taglineHiShort: "ज़मीन से संपूर्ण घर — मात्र 2 क्लिक में",
    heroTitle: "भारत का AI निर्माण सुपर ऐप",
    heroSub: "निर्माण, इंटीरियर, सोलर, डिज़ाइन, सामग्री, पेशेवर और प्रोजेक्ट ट्रैकिंग — एक प्रीमियम प्लेटफ़ॉर्म।",
    ctaStartProject: "मेरा प्रोजेक्ट शुरू करें",
    ctaFreeEstimate: "मुफ़्त अनुमान",
    servicesTitle: "बनाने के लिए सब कुछ",
    servicesSub: "एक स्क्रीन। बिना लंबे स्क्रॉल के।",
    trustTitle: "विश्वास और पारदर्शिता के लिए",
    techTitle: "आधुनिक तकनीक से संचालित",
    twoClickTitle: "वास्तविक 2-क्लिक अनुभव",
    twoClickSub: "क्लिक 1: क्या बनाना है। क्लिक 2: प्रोजेक्ट विवरण। फिर AI डैशबोर्ड खुलता है।",
    plannerTitle: "AI प्रोजेक्ट डैशबोर्ड",
    estimateTitle: "लागत कैलकुलेटर",
    generatePlan: "मेरी प्रोजेक्ट योजना बनाएं",
    downloadPdf: "कोटेशन PDF डाउनलोड",
    qualityLow: "कम",
    qualityStandard: "स्टैंडर्ड",
    qualityPremium: "प्रीमियम",
    qualityLuxury: "लक्ज़री",
    comingSoon: "जल्द आ रहा है",
    loginForAi: "2Click AI के लिए लॉग इन करें",
    nav: {
      home: "होम",
      build: "बिल्ड",
      estimate: "अनुमान",
      design: "डिज़ाइन",
      materials: "सामग्री",
      professionals: "पेशेवर",
      solar: "सोलर",
      projects: "प्रोजेक्ट",
      about: "हमारे बारे में",
      ai: "AI",
      profile: "प्रोफ़ाइल",
      services: "सेवाएँ",
    },
    projectTypes: [
      { id: "residential", en: "Residential", hi: "आवासीय" },
      { id: "commercial", en: "Commercial", hi: "व्यावसायिक" },
      { id: "industrial", en: "Industrial", hi: "औद्योगिक" },
      { id: "renovation", en: "Renovation", hi: "नवीनीकरण" },
      { id: "interior", en: "Interior", hi: "इंटीरियर" },
      { id: "solar", en: "Solar", hi: "सोलर" },
    ],
    services: [
      { id: "construction", en: "Construction", hi: "निर्माण", to: "/build" },
      { id: "architecture", en: "Architecture", hi: "वास्तुकला", to: "/consultants" },
      { id: "interior", en: "Interior", hi: "इंटीरियर", to: "/interior-boq" },
      { id: "solar", en: "Solar", hi: "सोलर", to: "/solar" },
      { id: "lidar", en: "LiDAR Survey", hi: "LiDAR सर्वे", to: "/technology" },
      { id: "vr", en: "3D / VR", hi: "3D / VR", to: "/technology" },
      { id: "materials", en: "Materials", hi: "सामग्री", to: "/store" },
      { id: "labour", en: "Labour", hi: "श्रम", to: "/freelancers" },
      { id: "contractor", en: "Contractor", hi: "ठेकेदार", to: "/freelancers" },
      { id: "pm", en: "Project Mgmt", hi: "प्रोजेक्ट", to: "/projects" },
    ],
    trust: [
      { en: "Verified professionals", hi: "सत्यापित पेशेवर" },
      { en: "Transparent pricing", hi: "पारदर्शी मूल्य" },
      { en: "Digital quotations", hi: "डिजिटल कोटेशन" },
      { en: "Project tracking", hi: "प्रोजेक्ट ट्रैकिंग" },
      { en: "Document vault", hi: "दस्तावेज़ वॉल्ट" },
      { en: "Secure payments", hi: "सुरक्षित भुगतान" },
    ],
    tech: [
      { en: "AI planning", hi: "AI योजना" },
      { en: "LiDAR ready", hi: "LiDAR तैयार" },
      { en: "3D walkthrough", hi: "3D वॉकथ्रू" },
      { en: "VR preview", hi: "VR पूर्वावलोकन" },
    ],
  },
};

export function useSuperCopy(lang) {
  const c = SUPER_COPY[lang] || SUPER_COPY.en;
  const tr = (item) => (lang === "hi" ? item.hi || item.en : item.en);
  return { c, tr };
}
